### create a new Chapter
POST http://localhost:8080/api/chapter/create
Accept: application/json
Content-Type: application/json

{
  "number": "02",
  "name": "Sysrgh",
  "level": "6384ceb4662c69dea3223fdb"
}

### get all levels
POST http://localhost:8080/api/chapter/getbylevel
Accept: application/json
Content-Type: application/json

{
  "level": "6384ceb4662c69dea3223fdb"
}
